# Generated by Django 6.0.6 on 2026-07-08 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_from', models.CharField(max_length=20)),
                ('time_to', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=50)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excuses', to='attendance.employee')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
