# Generated by Django 6.0.6 on 2026-07-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_activitylog_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='source',
            field=models.CharField(choices=[('attendance', 'حضور و انصراف'), ('excuse', 'الاستئذانات'), ('sick_leave', 'الطبيات'), ('vacation', 'الإجازات'), ('other', 'أخرى')], default='other', max_length=20),
        ),
    ]
