# Generated by Django 6.0.6 on 2026-07-21 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_activitylog_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('civil_id', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='vacation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vacations', to='attendance.supervisor'),
        ),
    ]
