# Generated by Django 6.0.6 on 2026-07-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_supervisor_vacation_reviewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
