# Generated by Django 6.0.6 on 2026-07-22 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_employee_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='رقم التلفون يجب أن يتكون من 8 أرقام بالضبط', regex='^\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='رقم التلفون يجب أن يتكون من 8 أرقام بالضبط', regex='^\\d{8}$')]),
        ),
    ]
