# Generated by Django 6.0.6 on 2026-07-22 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_employee_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='civil_id',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='الرقم المدني يجب أن يتكون من 12 رقم بالضبط', regex='^\\d{12}$')]),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='civil_id',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='الرقم المدني يجب أن يتكون من 12 رقم بالضبط', regex='^\\d{12}$')]),
        ),
    ]
