# Generated by Django 6.0.6 on 2026-07-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_alter_employee_civil_id_alter_supervisor_civil_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', 'إضافة'), ('update', 'تعديل'), ('delete', 'حذف'), ('view', 'عرض')], max_length=10),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='source',
            field=models.CharField(choices=[('attendance', 'حضور و انصراف'), ('excuse', 'الاستئذانات'), ('sick_leave', 'الطبيات'), ('vacation', 'الإجازات'), ('employee', 'الموظفين'), ('supervisor', 'المسؤولين'), ('other', 'أخرى')], default='other', max_length=20),
        ),
    ]
