# Generated by Django 6.0.6 on 2026-07-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_alter_activitylog_action_alter_activitylog_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
