# Generated by Django 6.0.6 on 2026-07-26 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_attendancerecord_late_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
