# Generated by Django 6.0.6 on 2026-07-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_alter_attendancerecord_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='is_opened_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
