# Generated by Django 6.0.6 on 2026-08-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_employee_photo_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, default='مهندس مبتدئ حاسوب', max_length=255, null=True),
        ),
    ]
