# Generated by Django 6.0.6 on 2026-08-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_employee_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, choices=[('مهندس مبتدئ حاسوب', 'مهندس مبتدئ حاسوب'), ('مهندس حاسوب', 'مهندس حاسوب'), ('مهندس أول', 'مهندس أول'), ('كبير المهندسين', 'كبير المهندسين')], max_length=255, null=True),
        ),
    ]
