# Generated by Django 6.0.6 on 2026-08-05 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_alter_employee_job_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='job_title',
            field=models.CharField(blank=True, choices=[('مهندس مبتدئ حاسوب', 'مهندس مبتدئ حاسوب'), ('مهندس حاسوب', 'مهندس حاسوب'), ('مهندس أول', 'مهندس أول'), ('كبير المهندسين', 'كبير المهندسين')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='supervisor_photos/'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
