# Generated by Django 6.0.6 on 2026-06-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('civil_id', models.CharField(max_length=12, unique=True)),
                ('nationality', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'training_person',
            },
        ),
    ]
