# Generated by Django 6.0.6 on 2026-06-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CivilRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civil_id', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('unified_number', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'training_civilrecord',
            },
        ),
    ]
