# Generated by Django 6.0.6 on 2026-07-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_civilrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilrecord',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='civilrecord',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
