# Generated by Django 6.0.6 on 2026-07-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_civilrecord_gender_civilrecord_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilrecord',
            name='unified_number',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
